---
title: "Potential research questions"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache = FALSE)
```

## Testing general predictions of Fisher's theorem

$~$

**1. Do traits correlated with fitness have lower heritabilities?**

Following Fisher's theorem and assuming a constant environment, in the absence of new variation, selection is expected to erode all additive genetic variation for fitness. One implication of this expectation is that traits that are correlated with fitness should show reduced additive genetic variance relative to those that are not correlated with fitness *(Robertson 1955b)*.

There are previous studies that have compared fitness related traits i.e. those implicated with reproduction, with morphological traits, which are assumed to have lesser relationships with fitness.

-   The problem is associating these traits with \_lifetime) fitness. This shouldn't be such a problem for us...

-   Multiple studies looking at this corollary use phenotypic correlations with fitness rather than genetic. Once again, this is no problem for us...

-   Even if there is lots of additive genetic variance for a trait and it is correlated with fitness, if fitness has a high environmental variance component the strength of selection on the trait will be weak.

*Houle (1992)* looks like an important meta-analysis type work.

**2. Do traits correlated with fitness have higher levels of both additive and residual variance**

Note that heritability can also decline with an increase in environmental variance and no decrease (or an increase) in genetic variance. If true, this makes a simple regression with heritability and fitness misleading.

Using evolvability as his metric, Houle (1992) found that characters assumed to be closely related to fitness have higher evolvabilities than do trait with looser relationships to fitness. This suggests that the negative relationship between fitness and heritability is due to increased environmental variance in fitness related traits, not a decrease in additive genetic variance.

$~$

## Testing hypotheses regarding sex-specific selection

$~$

**1. Is additive genetic variance for traits higher in males than it is in females?**

*Walsh and Lynch (2018)* raise an important point: to compare variances between traits, one needs a standardised measure. *Houle (1992)* suggests the coefficient of additive genetic variance, $CV_A = \sigma_A / \mu$, where $\mu$ is the trait mean. Houle coined this term ***evolvability***.

**2. Do males exhibit higher heritabilities for traits than females?**

**3. Are selection differentials across traits stronger for males than they are for females?**

$~$

## Testing hypotheses relating to sexually antagonstic selection

$~$

1.  **Is there a negative relationship between the intersex genetic correlation and sexual dimorphism?**

If there is, it means that a shared genetic architecture between the sexes constrains the ability of selection to move traits towards their separate female and male optimas.

Intralocus sexual conflict should therefore be stronger for traits that are more constrained by the intersex genetic correlation.

If there isn't, the resolution of intralocus sexual conflict may be easier than expected i.e. sharing a genome may not be the problem we think it is.

**2. Can we detect sexually antagonistic selection**

**3. Is SA selection stronger on reproductive traits than viability related traits?**

**4. Does SA selection positively correlate with sexual dimorphism?**

This one is a little tricky. One might expect a positive relationship, because why else would the trait be sexually dimorphic? But perhaps dimorphism has evolved to the extent that the conflict is resolved. The question is whether current dimorphism affects selection??

If a males trait optima = 5 and a females = 10. No dimorphism, while assuming equally strong selection on both sexes, would suggest a trait mean of 7.5 for both sexes. Alleles that increase the mean will be favoured in females but selected against in males.

Now if there is strong dimorphism. Selection on the trait stays the same - higher vales are selected in females and selected against in males. But females and males are more dissimilar now, such that alleles that effect males in one way don't necessarily affect females in the same way.

Upon reflection, I believe this is a way to test whether intralocus sexual conflict is ongoing in the DGRP population, or if it has been resolved by sexual dimorphism. If we observe a positive relationship between SA selection and dimorphism, this is indicative of ongoing sexual conflict i.e. dimorphism is incomplete. If there is a negative relationship, this is indicative of dimorphism being an effective resolution to sexual conflict. No relationship indicates that...

A broad prediction for this one still isn't clear for me.

4.  **Do genomes with greater across the board sexual dimorphism have higher fitness?**

The thinking here is that escaping sexual conflict increases fitness. Those DGRP that aren't dimorphic are stuck suffering the consequences of conflict. Whether this hypothesis stacks up is dependent on the existence of genetic variation for sexual dimorphism across a whole range of traits. It may be that dimorphism is trait rather than genotype specific.

$~$

## Other general questions that relate to natural selection

$~$

**1.  Is selection stronger on reproductive traits than it is on viability related traits?**

**2.  Is selection more concordant in stressful conditions? And does stress increase the strength of selection?**

Theory suggests it should, because male and female condition/fitness become more aligned in stressful environments. To illustrate this point, consider fitness in two contexts a) a benign environment where fitness depends on an individuals interaction with conspecifics and b) a stressful environment, where a large component of fitness is tied to viability/condition. The first context leaves plenty of room for sex-specific fitness, while the second is likely to effect the sexes in a similar way - they face a common hardship, which aligns fitness in the sexes.
